#!/usr/bin/env python3
"""Imports Material Symbols (Rounded) as Android VectorDrawables.

Usage: tools/import_icons.py
Downloads each symbol listed in ICONS (filled, habit icons) and UI_ICONS
(outlined, app chrome) from the google/material-design-icons repository
(Apache License 2.0) and writes res/drawable/ic_habit_<key>.xml and
res/drawable/ic_ui_<name>.xml. Re-run after editing the lists; keep ICONS in
sync with HabitIcons.kt.

Path data is rewritten with explicit separators: Android 5.x cannot parse the
compact form Material Symbols use (e.g. "7.5.5" meaning 7.5 and .5).
"""
import pathlib
import re
import urllib.request

ICONS = {
    "check": "check_circle", "smoking": "smoking_rooms", "smoke_free": "smoke_free",
    "vaping": "vaping_rooms", "sweets": "cookie", "icecream": "icecream", "cake": "cake",
    "pizza": "local_pizza", "food": "restaurant", "burger": "lunch_dining",
    "fruit": "nutrition", "greens": "eco", "coffee": "local_cafe",
    "tea": "emoji_food_beverage", "drinks": "local_bar", "beer": "sports_bar",
    "wine": "wine_bar", "water": "water_drop", "water_glass": "water_full",
    "workout": "fitness_center", "walk": "directions_walk", "run": "directions_run",
    "bike": "directions_bike", "swim": "pool", "hike": "hiking",
    "football": "sports_soccer", "basketball": "sports_basketball",
    "meditation": "self_improvement", "selfcare": "spa", "sleep": "bedtime",
    "wake": "wb_sunny", "alarm": "alarm", "read": "menu_book", "journal": "edit_note",
    "medication": "medication", "love": "favorite", "mood": "mood",
    "bad_mood": "sentiment_dissatisfied", "phone": "phone_iphone", "call": "call",
    "tv": "tv", "gaming": "sports_esports", "music": "music_note", "piano": "piano",
    "art": "brush", "photo": "photo_camera", "cleaning": "cleaning_services",
    "shower": "shower", "teeth": "dentistry", "pets": "pets", "plants": "potted_plant",
    "savings": "savings", "shopping": "shopping_cart", "code": "code", "study": "school",
    "language": "translate", "work": "work", "weight": "monitor_weight", "timer": "timer",
    "star": "star", "energy": "bolt", "mind": "psychology", "toilet": "wc",
    "kindness": "volunteer_activism", "stop": "do_not_disturb_on",
}

UI_ICONS = [
    "add", "add_photo_alternate", "add_to_home_screen", "arrow_back", "calendar_month",
    "check", "chevron_left", "chevron_right", "close", "delete", "edit", "expand_more",
    "format_list_bulleted", "widgets",
]

BASE = ("https://raw.githubusercontent.com/google/material-design-icons/master/"
        "symbols/web/{0}/materialsymbolsrounded/{0}{1}_24px.svg")
OUT = pathlib.Path(__file__).resolve().parent.parent / "app/src/main/res/drawable"

TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Material Symbols "{symbol}" (Rounded{style}), Apache License 2.0. Generated by tools/import_icons.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="960"
    android:viewportHeight="960">
    <group android:translateY="960">
{paths}
    </group>
</vector>
"""


NUMBER = re.compile(r"[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?")
TOKEN = re.compile(r"[A-Za-z]|" + NUMBER.pattern)


def normalize(path_data):
    """Re-emits path data with every command and number separated by a space."""
    tokens = TOKEN.findall(path_data)
    if "".join(tokens) != re.sub(r"[\s,]", "", path_data):
        raise ValueError(f"unexpected path data: {path_data[:60]}")
    # Leading zeros ("-0.5" rather than "-.5") keep old parsers on the safe side.
    return " ".join(re.sub(r"^([-+]?)\.", r"\g<1>0.", t) for t in tokens)


def write(name, symbol, filled, fill_color):
    svg = urllib.request.urlopen(BASE.format(symbol, "_fill1" if filled else "")).read().decode()
    paths = re.findall(r'<path d="([^"]+)"', svg)
    body = "\n".join(
        f'        <path\n            android:fillColor="{fill_color}"\n'
        f'            android:pathData="{normalize(d)}" />' for d in paths)
    style = ", filled" if filled else ""
    (OUT / f"{name}.xml").write_text(TEMPLATE.format(symbol=symbol, style=style, paths=body))


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for key, symbol in ICONS.items():
        write(f"ic_habit_{key}", symbol, filled=True, fill_color="@android:color/white")
    for symbol in UI_ICONS:
        write(f"ic_ui_{symbol}", symbol, filled=False, fill_color="@color/text_primary")
    print(f"wrote {len(ICONS) + len(UI_ICONS)} icons to {OUT}")


if __name__ == "__main__":
    main()
