#!/usr/bin/env python3
"""Imports Material Symbols (Rounded, filled) as Android VectorDrawables.

Usage: tools/import_icons.py
Downloads each symbol listed in ICONS from the google/material-design-icons
repository (Apache License 2.0) and writes res/drawable/ic_habit_<key>.xml.
Re-run after editing ICONS; keep the list in sync with HabitIcons.kt.
"""
import pathlib
import re
import urllib.request

ICONS = {
    "check": "check_circle", "smoking": "smoking_rooms", "smoke_free": "smoke_free",
    "vaping": "vaping_rooms", "sweets": "cookie", "icecream": "icecream", "cake": "cake",
    "pizza": "local_pizza", "food": "restaurant", "burger": "lunch_dining",
    "fruit": "nutrition", "greens": "eco", "coffee": "local_cafe",
    "tea": "emoji_food_beverage", "drinks": "local_bar", "beer": "sports_bar",
    "wine": "wine_bar", "water": "water_drop", "water_glass": "water_full",
    "workout": "fitness_center", "walk": "directions_walk", "run": "directions_run",
    "bike": "directions_bike", "swim": "pool", "hike": "hiking",
    "football": "sports_soccer", "basketball": "sports_basketball",
    "meditation": "self_improvement", "selfcare": "spa", "sleep": "bedtime",
    "wake": "wb_sunny", "alarm": "alarm", "read": "menu_book", "journal": "edit_note",
    "medication": "medication", "love": "favorite", "mood": "mood",
    "bad_mood": "sentiment_dissatisfied", "phone": "phone_iphone", "call": "call",
    "tv": "tv", "gaming": "sports_esports", "music": "music_note", "piano": "piano",
    "art": "brush", "photo": "photo_camera", "cleaning": "cleaning_services",
    "shower": "shower", "teeth": "dentistry", "pets": "pets", "plants": "potted_plant",
    "savings": "savings", "shopping": "shopping_cart", "code": "code", "study": "school",
    "language": "translate", "work": "work", "weight": "monitor_weight", "timer": "timer",
    "star": "star", "energy": "bolt", "mind": "psychology", "toilet": "wc",
    "kindness": "volunteer_activism", "stop": "do_not_disturb_on",
}

BASE = ("https://raw.githubusercontent.com/google/material-design-icons/master/"
        "symbols/web/{0}/materialsymbolsrounded/{0}_fill1_24px.svg")
OUT = pathlib.Path(__file__).resolve().parent.parent / "app/src/main/res/drawable"

TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Material Symbols "{symbol}" (Rounded, filled), Apache License 2.0. Generated by tools/import_icons.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="960"
    android:viewportHeight="960">
    <group android:translateY="960">
{paths}
    </group>
</vector>
"""


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for key, symbol in ICONS.items():
        svg = urllib.request.urlopen(BASE.format(symbol)).read().decode()
        paths = re.findall(r'<path d="([^"]+)"', svg)
        body = "\n".join(
            f'        <path\n            android:fillColor="@android:color/white"\n'
            f'            android:pathData="{d}" />' for d in paths)
        (OUT / f"ic_habit_{key}.xml").write_text(TEMPLATE.format(symbol=symbol, paths=body))
    print(f"wrote {len(ICONS)} icons to {OUT}")


if __name__ == "__main__":
    main()
